import express from 'express';
import cors from 'cors';
import helloController  from "./controllers/hello-controller.js";
import userController   from "./controllers/user-controller.js";
import tuitsController  from "./controllers/tuits-controller.js";
const app = express();
const cors_options = {origin : "https://playful-cendol-680fc0.netlify.app"};
app.use(cors(cors_options));
app.use(express.json());
helloController(app);
userController(app);
tuitsController(app);
app.listen(4000);